---
- name: Install load balancer packages
  package:
    name: "{{ payload }}"
    state: present
  notify:
    - start {{ payload }}


- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - restart {{ payload }}

